"""Deterministic, research-only market discovery (Loop.md Phase 0.95).

The scanner broadens the research pool without broadening trading authority.
It accepts a provenance-bearing universe from a provider, validates every
instrument/evidence edge, computes replayable market/news features and returns
a ranked :class:`DiscoveryPool`.  It has no dependency on CandidateOrder,
RiskEngine, ConfirmationService, ExecutionEngine or a broker.

An LLM may help an upstream provider describe a theme, but an LLM-only ticker
is rejected here: each seed must already be instrument-resolved and carry at
least one dated URL-backed evidence item.  This keeps discovery auditable and
makes identical inputs produce identical rankings.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from enum import Enum
import json
from pathlib import Path
from typing import Any, Callable, Optional, Protocol

from pydantic import BaseModel, ConfigDict, Field, field_validator

from swing_trader.datafeed import DataFeedError
from swing_trader.interfaces import Bar, DataFeed, NewsItem

__all__ = [
    "DiscoveryCandidate",
    "DiscoveryEvidence",
    "DiscoveryFeatures",
    "DiscoveryPool",
    "DiscoverySeed",
    "DiscoveryTheme",
    "DiscoveryUniverseProvider",
    "EvidenceKind",
    "MarketDiscoveryScanner",
    "JsonDiscoveryUniverse",
    "KnowledgeDiscoveryUniverse",
    "CompositeDiscoveryUniverse",
    "RejectedDiscovery",
    "StaticDiscoveryUniverse",
]


class EvidenceKind(str, Enum):
    COMPANY = "company"
    FILING = "filing"
    SUPPLY_CHAIN = "supply_chain"
    ETF_CONSTITUENT = "etf_constituent"
    EARNINGS = "earnings"
    NEWS = "news"


class DiscoveryEvidence(BaseModel):
    model_config = ConfigDict(frozen=True)

    kind: EvidenceKind
    source: str = Field(min_length=1, max_length=120)
    url: str = Field(pattern=r"^https?://")
    observed_at: datetime
    summary: str = Field(min_length=1, max_length=500)
    confidence: float = Field(ge=0.0, le=1.0)

    @field_validator("observed_at")
    @classmethod
    def _aware(cls, value: datetime) -> datetime:
        if value.tzinfo is None or value.utcoffset() is None:
            raise ValueError("observed_at must be timezone-aware")
        return value


class DiscoverySeed(BaseModel):
    """One resolved instrument-to-theme/component relationship."""

    model_config = ConfigDict(frozen=True)

    symbol: str = Field(min_length=1, max_length=32)
    display_name: str = Field(min_length=1, max_length=160)
    market: str = Field(pattern=r"^(US|HK|CN)$")
    exchange: str = Field(min_length=1, max_length=32)
    currency: str = Field(min_length=3, max_length=3)
    theme: str = Field(min_length=1, max_length=120)
    component: str = Field(min_length=1, max_length=160)
    relationship: str = Field(min_length=1, max_length=500)
    instrument_resolved: bool = True
    evidence: list[DiscoveryEvidence] = Field(min_length=1)


class DiscoveryTheme(BaseModel):
    """A broad research direction, never a preselected company/component."""

    model_config = ConfigDict(frozen=True)

    name: str = Field(min_length=1, max_length=120)
    query: str = Field(min_length=3, max_length=500)


class DiscoveryFeatures(BaseModel):
    adv20: float
    volume_ratio: float
    trend_20d_pct: float
    relative_strength_20d_pct: float
    news_heat: float
    event_score: float
    moat_score: float
    etf_change_score: float


class DiscoveryCandidate(BaseModel):
    symbol: str
    display_name: str
    market: str
    exchange: str
    currency: str
    theme: str
    component: str
    relationship: str
    score: float = Field(ge=0.0, le=100.0)
    rank: int = Field(ge=1)
    reasons: list[str] = Field(default_factory=list)
    features: DiscoveryFeatures
    evidence: list[DiscoveryEvidence]


class RejectedDiscovery(BaseModel):
    symbol: str
    reason: str


class DiscoveryPool(BaseModel):
    market: str
    as_of: datetime
    candidates: list[DiscoveryCandidate] = Field(default_factory=list)
    rejected: list[RejectedDiscovery] = Field(default_factory=list)
    source_count: int = 0


class DiscoveryUniverseProvider(Protocol):
    def seeds(self, market: str, as_of: datetime) -> list[DiscoverySeed]: ...


class StaticDiscoveryUniverse:
    """Deterministic provider used by the bundled evidence catalog and tests."""

    def __init__(self, seeds: list[DiscoverySeed]) -> None:
        self._seeds = list(seeds)

    def seeds(self, market: str, as_of: datetime) -> list[DiscoverySeed]:
        del as_of
        key = market.upper()
        return [seed for seed in self._seeds if seed.market == key]


class JsonDiscoveryUniverse:
    """Load evidence-bearing seeds generated by an external broad screener.

    The scanner deliberately does not hard-code a list of fashionable tickers.
    A market-data/filing/news collector writes a JSON array to this file; every
    read is re-validated through :class:`DiscoverySeed`, so malformed or
    LLM-only guesses fail closed. Missing/invalid files yield an empty universe.
    """

    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)

    def seeds(self, market: str, as_of: datetime) -> list[DiscoverySeed]:
        del as_of
        try:
            payload = json.loads(self.path.read_text(encoding="utf-8"))
            rows = payload.get("seeds", []) if isinstance(payload, dict) else payload
            parsed = [DiscoverySeed.model_validate(row) for row in rows]
        except (OSError, ValueError, TypeError):
            return []
        key = market.upper()
        return [seed for seed in parsed if seed.market == key]


class CompositeDiscoveryUniverse:
    """Union sources deterministically with earlier-provider precedence."""

    def __init__(self, providers: list[DiscoveryUniverseProvider]) -> None:
        self.providers = list(providers)

    def seeds(self, market: str, as_of: datetime) -> list[DiscoverySeed]:
        rows: list[DiscoverySeed] = []
        seen: set[str] = set()
        for provider in self.providers:
            try:
                supplied = provider.seeds(market, as_of)
            except Exception:
                continue
            for row in sorted(supplied, key=lambda item: (item.symbol, item.theme)):
                if row.symbol in seen:
                    continue
                seen.add(row.symbol)
                rows.append(row)
        return sorted(rows, key=lambda row: (row.symbol, row.theme))


class KnowledgeDiscoveryUniverse:
    """Discover instruments already evidenced in the dated knowledge base.

    Semantic retrieval broadens beyond the static watchlist using high-level
    themes. A hit becomes a seed only when the document has source provenance
    and its symbol resolves exactly in the requested market. The relationship
    text comes from the stored source document, not an LLM guess.
    """

    def __init__(
        self,
        knowledge: Any,
        instrument_search: Any,
        themes: list[DiscoveryTheme],
        *,
        hits_per_theme: int = 20,
    ) -> None:
        self.knowledge = knowledge
        self.instrument_search = instrument_search
        self.themes = list(themes)
        self.hits_per_theme = hits_per_theme

    def seeds(self, market: str, as_of: datetime) -> list[DiscoverySeed]:
        if self.knowledge is None or self.instrument_search is None:
            return []
        best: dict[str, tuple[float, DiscoverySeed]] = {}
        for theme in sorted(self.themes, key=lambda row: (row.name, row.query)):
            try:
                hits = self.knowledge.search(theme.query, k=self.hits_per_theme)
            except Exception:
                continue
            for hit in hits:
                doc = hit.get("document")
                if doc is None or not getattr(doc, "source_url", ""):
                    continue
                score = float(hit.get("score") or 0.0)
                for raw_symbol in sorted(getattr(doc, "symbols", []) or []):
                    resolved = self._resolve(str(raw_symbol), market)
                    if resolved is None:
                        continue
                    evidence = DiscoveryEvidence(
                        kind=self._evidence_kind(getattr(doc, "doc_type", "")),
                        source=str(getattr(doc, "publisher", "unknown")),
                        url=str(doc.source_url),
                        observed_at=getattr(doc, "retrieved_at", as_of),
                        summary=str(getattr(doc, "title", "") or hit.get("snippet") or "")[:500],
                        confidence=_clamp(score),
                    )
                    seed = DiscoverySeed(
                        symbol=resolved.canonical_symbol,
                        display_name=resolved.display_name,
                        market=market.upper(), exchange=resolved.exchange,
                        currency=resolved.currency, theme=theme.name,
                        component="evidence-backed supply-chain relationship",
                        relationship=str(hit.get("snippet") or evidence.summary)[:500],
                        instrument_resolved=True, evidence=[evidence],
                    )
                    current = best.get(seed.symbol)
                    if current is None or (score, theme.name) > (current[0], current[1].theme):
                        best[seed.symbol] = (score, seed)
        return [best[symbol][1] for symbol in sorted(best)]

    def _resolve(self, symbol: str, market: str):
        from swing_trader.instruments import MarketScope

        try:
            result = self.instrument_search.search(
                symbol, market=MarketScope(market.upper()), limit=10
            )
        except Exception:
            return None
        matches = getattr(result, "matches", result)
        wanted = symbol.strip().upper()
        return next(
            (row for row in matches if row.canonical_symbol.upper() == wanted),
            None,
        )

    @staticmethod
    def _evidence_kind(doc_type: Any) -> EvidenceKind:
        value = str(getattr(doc_type, "value", doc_type)).lower()
        if "filing" in value:
            return EvidenceKind.FILING
        if "earning" in value or "report" in value:
            return EvidenceKind.EARNINGS
        return EvidenceKind.NEWS


_EVENT_TERMS = (
    "earnings", "guidance", "contract", "order", "capex", "capacity",
    "launch", "approval", "partnership", "backlog", "产能", "订单", "财报",
    "指引", "获批", "合作",
)


def _clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, value))


def _return_20d(bars: list[Bar]) -> float:
    start = bars[-21].close
    return 0.0 if start <= 0 else (bars[-1].close / start - 1.0) * 100.0


def _adv20(bars: list[Bar]) -> float:
    tail = bars[-20:]
    return sum(bar.close * bar.volume for bar in tail) / len(tail)


def _volume_ratio(bars: list[Bar]) -> float:
    history = bars[-21:-1]
    baseline = sum(bar.volume for bar in history) / len(history)
    return 0.0 if baseline <= 0 else bars[-1].volume / baseline


def _recent_news(items: list[NewsItem], now: datetime) -> list[NewsItem]:
    cutoff = now - timedelta(days=14)
    return sorted(
        [item for item in items if item.ts >= cutoff],
        key=lambda item: (item.ts, item.headline, item.url),
        reverse=True,
    )


class MarketDiscoveryScanner:
    """Replayable broad-screen → validation → ranking research funnel."""

    def __init__(
        self,
        feed: DataFeed,
        universe: DiscoveryUniverseProvider,
        *,
        benchmark_symbol: str,
        min_adv: float,
        min_score: float = 45.0,
        max_candidates: int = 12,
        max_bar_age_days: int = 10,
        max_evidence_age_days: int = 730,
        instrument_validator: Optional[Callable[[DiscoverySeed], bool]] = None,
        clock: Callable[[], datetime] = lambda: datetime.now(timezone.utc),
    ) -> None:
        self.feed = feed
        self.universe = universe
        self.benchmark_symbol = benchmark_symbol
        self.min_adv = min_adv
        self.min_score = min_score
        self.max_candidates = max_candidates
        self.max_bar_age_days = max_bar_age_days
        self.max_evidence_age_days = max_evidence_age_days
        self.instrument_validator = instrument_validator or (
            lambda seed: seed.instrument_resolved
        )
        self.clock = clock

    def scan(self, market: str) -> DiscoveryPool:
        now = self.clock()
        market = market.upper()
        rejected: list[RejectedDiscovery] = []
        accepted: list[DiscoveryCandidate] = []
        benchmark_return = self._benchmark_return()
        seeds = sorted(
            self.universe.seeds(market, now), key=lambda s: (s.symbol, s.theme)
        )

        seen: set[str] = set()
        for seed in seeds:
            if seed.symbol in seen:
                rejected.append(RejectedDiscovery(
                    symbol=seed.symbol, reason="duplicate symbol in discovery universe"
                ))
                continue
            seen.add(seed.symbol)
            reason = self._validate_seed(seed, market, now)
            if reason:
                rejected.append(RejectedDiscovery(symbol=seed.symbol, reason=reason))
                continue
            try:
                bars = self.feed.get_bars(seed.symbol, "1d", limit=80)
            except (DataFeedError, ValueError) as exc:
                rejected.append(RejectedDiscovery(
                    symbol=seed.symbol, reason=f"market data unavailable: {exc}"
                ))
                continue
            if len(bars) < 21:
                rejected.append(RejectedDiscovery(
                    symbol=seed.symbol, reason="fewer than 21 daily bars"
                ))
                continue
            bars = sorted(bars, key=lambda bar: bar.ts)
            bar_age = (now - bars[-1].ts).total_seconds() / 86400.0
            if bar_age > self.max_bar_age_days:
                rejected.append(RejectedDiscovery(
                    symbol=seed.symbol, reason=f"last bar is {bar_age:.1f} days old"
                ))
                continue
            adv = _adv20(bars)
            if adv < self.min_adv:
                rejected.append(RejectedDiscovery(
                    symbol=seed.symbol,
                    reason=f"ADV20 {adv:.0f} below minimum {self.min_adv:.0f}",
                ))
                continue
            try:
                news = self.feed.get_news(seed.symbol, limit=20)
            except (DataFeedError, ValueError):
                news = []
            recent = _recent_news(news, now)
            features = self._features(seed, bars, recent, benchmark_return)
            score = self._score(features)
            if score < self.min_score:
                rejected.append(RejectedDiscovery(
                    symbol=seed.symbol,
                    reason=f"score {score:.1f} below threshold {self.min_score:.1f}",
                ))
                continue
            accepted.append(DiscoveryCandidate(
                symbol=seed.symbol,
                display_name=seed.display_name,
                market=seed.market,
                exchange=seed.exchange,
                currency=seed.currency,
                theme=seed.theme,
                component=seed.component,
                relationship=seed.relationship,
                score=score,
                rank=1,
                reasons=self._reasons(features),
                features=features,
                evidence=sorted(seed.evidence, key=lambda e: (e.kind.value, e.url)),
            ))

        accepted.sort(key=lambda item: (-item.score, item.symbol))
        accepted = accepted[: self.max_candidates]
        accepted = [item.model_copy(update={"rank": idx + 1})
                    for idx, item in enumerate(accepted)]
        return DiscoveryPool(
            market=market,
            as_of=now,
            candidates=accepted,
            rejected=sorted(rejected, key=lambda item: (item.symbol, item.reason)),
            source_count=len(seeds),
        )

    def _benchmark_return(self) -> float:
        try:
            bars = sorted(
                self.feed.get_bars(self.benchmark_symbol, "1d", limit=80),
                key=lambda bar: bar.ts,
            )
        except (DataFeedError, ValueError):
            return 0.0
        return _return_20d(bars) if len(bars) >= 21 else 0.0

    def _validate_seed(
        self, seed: DiscoverySeed, market: str, now: datetime
    ) -> Optional[str]:
        if seed.market != market:
            return f"seed market {seed.market} does not match scanner market {market}"
        if not self.instrument_validator(seed):
            return "instrument unresolved"
        if not seed.evidence:
            return "no provenance evidence"
        cutoff = now - timedelta(days=self.max_evidence_age_days)
        if all(item.observed_at < cutoff for item in seed.evidence):
            return "all relationship evidence is stale"
        return None

    def _features(
        self,
        seed: DiscoverySeed,
        bars: list[Bar],
        news: list[NewsItem],
        benchmark_return: float,
    ) -> DiscoveryFeatures:
        trend = _return_20d(bars)
        event_hits = sum(
            1 for item in news
            if any(term in item.headline.lower() for term in _EVENT_TERMS)
        )
        structural = [
            item.confidence for item in seed.evidence
            if item.kind in {
                EvidenceKind.COMPANY,
                EvidenceKind.FILING,
                EvidenceKind.SUPPLY_CHAIN,
            }
        ]
        return DiscoveryFeatures(
            adv20=_adv20(bars),
            volume_ratio=_volume_ratio(bars),
            trend_20d_pct=trend,
            relative_strength_20d_pct=trend - benchmark_return,
            news_heat=_clamp(len(news) / 5.0),
            event_score=_clamp(event_hits / 3.0),
            moat_score=(sum(structural) / len(structural) if structural else 0.0),
            etf_change_score=(
                1.0 if any(item.kind is EvidenceKind.ETF_CONSTITUENT
                           for item in seed.evidence) else 0.0
            ),
        )

    @staticmethod
    def _score(features: DiscoveryFeatures) -> float:
        trend = _clamp((features.trend_20d_pct + 5.0) / 25.0)
        relative = _clamp((features.relative_strength_20d_pct + 5.0) / 20.0)
        volume = _clamp((features.volume_ratio - 1.0) / 2.0)
        score = 100.0 * (
            0.20 * trend
            + 0.15 * relative
            + 0.15 * volume
            + 0.15 * features.news_heat
            + 0.10 * features.event_score
            + 0.20 * features.moat_score
            + 0.05 * features.etf_change_score
        )
        return round(score, 4)

    @staticmethod
    def _reasons(features: DiscoveryFeatures) -> list[str]:
        reasons = [
            f"20d trend {features.trend_20d_pct:+.1f}%",
            f"relative strength {features.relative_strength_20d_pct:+.1f}%",
            f"volume {features.volume_ratio:.1f}x 20d average",
            f"evidence confidence {features.moat_score:.2f}",
        ]
        if features.news_heat > 0:
            reasons.append(f"news heat {features.news_heat:.2f}")
        if features.event_score > 0:
            reasons.append(f"event catalyst {features.event_score:.2f}")
        if features.etf_change_score > 0:
            reasons.append("ETF constituent-change evidence")
        return reasons
